### ISSUE TITLE
Script crashes when there are no _R4_ files

### ISSUE THREAD

**Issue by CharlesJB** [sebhtml/FastDemultiplexer#1]
Some sequencing runs produce only _R1_, _R2_ and _R3_ files. 

Problematic lines:

[232] self.m_r4Files=[]
[...]
[256] self.m_reader4=FileReader(self.m_directory+"/"+self.m_r4Files[self.m_current])
[...]
[271] return [self.m_reader1.getNext(), self.m_reader2.getNext(), self.m_reader3.getNext(), self.m_reader4.getNext()]
[...]
[369] outputDirectory.write(project,sample,lane,[sequenceTuple[0],sequenceTuple[3]])

**Comment by sebhtml** [comment]
The tool assumes that there are 4 files for each group: R1, R2, R3, R4. This information is in the README.

A work-around for ChIP-Seq is to mv the R3 to R4 and to sym. link R2 to R3

R1

R2

R3 -> R2

R4 (old R3)

**Comment by sebhtml** [comment]
Paths to reproduce the problem on colosse:

/rap/nne-790-ab/Instruments/Illumina_HiSeq_1000_Hellbound/130131_SNL131_0070_AC1MMMACXX/SampleSheet.csv

/rap/nne-790-ab/Instruments/Illumina_HiSeq_1000_Hellbound/130131_SNL131_0070_AC1MMMACXX/Convert_binary_to_FastQ_1

**Comment by CharlesJB** [comment]
??

**Comment by sebhtml** [comment]
At the moment, you need to do some symbolic links.

Create-R1-R2-R3-R4-Tree-from-R1-R2-R3-Tree.sh will do that for you.
