### ISSUE TITLE
Typo in readme?

### ISSUE THREAD

**Issue by ghost** [sebhtml/FastDemultiplexer#2]
"Basically, for each cluster on the flow cell, there will be 4 sequences:
R1, R2, R3, R4. R2 and R4 are the indexes, or bar-codes, and R1 and R2 are the 
sequences."

Aren't R1 and R4 the read sequences, R2 and R3 the indices?

At least my data was structured like that and after running the script, both read sequences were classified properly from R1 and R4.

**Comment by sebhtml** [comment]
You are right !

Thanks for the feedback. I fixed this.

9ba58e8d8010659c2ca5112dbd3cd3f7dd766a8c
