### ISSUE TITLE
Demultiplex on R3 only

### ISSUE THREAD

**Issue by droplet-lab** [sebhtml/FastDemultiplexer#8]
Hi Sebastien,

Thank you so much for making this tool. I was wondering, I have R1 R2 R3 and R4 files, but would like to only demultiplex on R3 (not R2 and R3).

How would you recommend me doing this? I'd like to use this to demultiplex indrops v3 files: https://github.com/indrops/indrops

Cheers

**Comment by sebhtml** [comment]
You can rename your *R2* and *R3* files to *OLD_R2* and *OLD_R3*.

Then, do a symbolic link ("ln -s foo") from OLD_R3 to R2, and from OLD_R3 on R3.
This way, only OLD_R3 is used.

In your sample sheet, put the same barcodes for R2 and R3 (which both point to OLD_R3).

Let me know if that works for you.

**Comment by droplet-lab** [comment]
Thanks a lotSebastien, I have found another solution that works, but will try yours if I see anything suspicious with the other method!
